name: Install PHP Workflow

on:
  workflow_call:
    inputs:
      php_version:
        description: 'PHP Version to install'
        default: '8.2'
        required: true
        type: string

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  install-php:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: ./.github/actions/setup-php
        with:
          php_version: ${{inputs.php_version}}

